id: P003161
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4346
  title: གཏེར་འབྱུང་ཆེན་མོ་དང་དྲི་བ་སོགས།
  author: ''
  volumes:
    526b7157488549ad80dba0d4c8b8758b:
      image_group_id: I3CN4566
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
